# Docker Compose for Zeabur Deployment
# This file shows the service configuration for reference

version: '3.8'

services:
  # PostgreSQL Database (deployed separately on Zeabur)
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: zeabur
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Qdrant Vector Database
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    ports:
      - "6333:6333"
      - "6334:6334"  # gRPC port
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      QDRANT__SERVICE__HTTP_PORT: 6333
      QDRANT__SERVICE__GRPC_PORT: 6334
      QDRANT__LOG_LEVEL: INFO

  # ConceptDB API Server
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      QDRANT_URL: http://qdrant:6333
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      USE_SIMPLE_VECTOR: "false"
      EVOLUTION_PHASE: "1"
      CONCEPT_RATIO: "0.1"
      API_HOST: 0.0.0.0
      API_PORT: 8000
    depends_on:
      - postgres
      - qdrant
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_data:
  qdrant_data: