databases:
  # PostgreSQL Database (使用 Render 管理的數據庫)
  - name: conceptdb-postgres
    databaseName: conceptdb
    user: concept_user
    plan: free  # 或 starter

services:

  # Qdrant Vector Database
  - type: web
    name: conceptdb-qdrant
    env: docker
    plan: free  # 使用免費計劃
    dockerCommand: ./qdrant
    dockerfilePath: ./docker/qdrant.Dockerfile
    envVars:
      - key: QDRANT_LOG_LEVEL
        value: INFO

  # ConceptDB API
  - type: web
    name: conceptdb-api
    env: python
    plan: free  # 使用免費計劃
    pythonVersion: "3.11"  # 指定 Python 版本
    buildCommand: pip install -r requirements-production.txt
    startCommand: python -m uvicorn src.api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: conceptdb-postgres
          property: connectionString
      - key: POSTGRES_URL
        fromDatabase:
          name: conceptdb-postgres
          property: connectionString
      - key: QDRANT_URL
        fromService:
          name: conceptdb-qdrant
          type: web
          property: hostport
      - key: EVOLUTION_PHASE
        value: "1"
      - key: CONCEPT_RATIO
        value: "0.1"
    autoDeploy: true

  # Web Studio (Optional)
  - type: web
    name: conceptdb-studio
    env: node
    plan: free  # 使用免費計劃
    buildCommand: cd studio && npm install && npm run build
    startCommand: cd studio && npm run start
    envVars:
      - key: NEXT_PUBLIC_CONCEPTDB_URL
        fromService:
          name: conceptdb-api
          type: web
          property: hostport